fix(secret_s3): add quote around port
opf/helm-charts pull request #102
Opened 2024-03-28 08:31 UTC by morganbasset

2024-03-28 10:18 UTC, machisuji commented
@morganbasset Thank you for the PR! Out of curiosity, what is the error that can be caused by not quoting this?

Either way I think the PR is fine, but you will need to adjust the spec too to make it green again! See https://github.com/opf/helm-charts/blob/main/spec/charts/openproject/s3_spec.rb#L26

2024-03-28 10:19 UTC, machisuji requested changes
👍 Please amend the respective spec too.

2024-03-28 10:27 UTC, oliverguenther approved these changes

2024-03-28 10:37 UTC, machisuji approved these changes

2024-03-28 10:37 UTC, merged

2024-03-29 08:32 UTC, morganbasset commented
> @morganbasset Thank you for the PR! Out of curiosity, what is the error that can be caused by not quoting this?
> 
> Either way I think the PR is fine, but you will need to adjust the spec too to make it green again! See https://github.com/opf/helm-charts/blob/main/spec/charts/openproject/s3_spec.rb#L26

Hi, this is the error I get when the value in not quoted
`failed to create resource: Secret in version "v1" cannot be handled as a Secret: json: cannot unmarshal number into Go struct field Secret.stringData of type string: failed to create resource: Secret in version "v1" cannot be handled as a Secret: json: cannot unmarshal number into Go struct field Secret.stringData of type string`

Thanks for merging the PR
;)